# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='haha', max_length=32),
            preserve_default=False,
        ),
    ]
